// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protobuf-net/generated_modified.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.TestProto {

  /// <summary>Holder for reflection information generated from protobuf-net/generated_modified.proto</summary>
  public static partial class GeneratedModifiedReflection {

    #region Descriptor
    /// <summary>File descriptor for protobuf-net/generated_modified.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GeneratedModifiedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVwcm90b2J1Zi1uZXQvZ2VuZXJhdGVkX21vZGlmaWVkLnByb3RvItkBChFE",
            "YXRhQ2hhbmdlZFB1Yk1zZxIRCglUdXJiaW5lSWQYASABKAkSGwoIRGF0ZVRp",
            "bWUYAiABKAsyCS5EYXRlVGltZRIuCgZWYWx1ZXMYAyADKAsyHi5EYXRhQ2hh",
            "bmdlZFB1Yk1zZy5WYWx1ZXNFbnRyeRIbChNOZWVkc1dyaXRpbmdUb1JlZGlz",
            "GAQgASgIEhgKBkFtb3VudBgFIAEoCzIILkRlY2ltYWwaLQoLVmFsdWVzRW50",
            "cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASKFAgoIRGF0ZVRp",
            "bWUSDQoFdmFsdWUYASABKBISJgoFc2NhbGUYAiABKA4yFy5EYXRlVGltZS5U",
            "aW1lU3BhblNjYWxlEiQKBGtpbmQYAyABKA4yFi5EYXRlVGltZS5EYXRlVGlt",
            "ZUtpbmQiZwoNVGltZVNwYW5TY2FsZRIICgREQVlTEAASCQoFSE9VUlMQARIL",
            "CgdNSU5VVEVTEAISCwoHU0VDT05EUxADEhAKDE1JTExJU0VDT05EUxAEEgkK",
            "BVRJQ0tTEAUSCgoGTUlOTUFYEA8iMwoMRGF0ZVRpbWVLaW5kEg8KC1VOU1BF",
            "Q0lGSUVEEAASBwoDVVRDEAESCQoFTE9DQUwQAiI0CgdEZWNpbWFsEgoKAmxv",
            "GAEgASgEEgoKAmhpGAIgASgNEhEKCXNpZ25TY2FsZRgDIAEoDUIcqgIZR29v",
            "Z2xlLlByb3RvYnVmLlRlc3RQcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.TestProto.DataChangedPubMsg), global::Google.Protobuf.TestProto.DataChangedPubMsg.Parser, new[]{ "TurbineId", "DateTime", "Values", "NeedsWritingToRedis", "Amount" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.TestProto.DateTime), global::Google.Protobuf.TestProto.DateTime.Parser, new[]{ "Value", "Scale", "Kind" }, null, new[]{ typeof(global::Google.Protobuf.TestProto.DateTime.Types.TimeSpanScale), typeof(global::Google.Protobuf.TestProto.DateTime.Types.DateTimeKind) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.TestProto.Decimal), global::Google.Protobuf.TestProto.Decimal.Parser, new[]{ "Lo", "Hi", "SignScale" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DataChangedPubMsg : pb::IMessage<DataChangedPubMsg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DataChangedPubMsg> _parser = new pb::MessageParser<DataChangedPubMsg>(() => new DataChangedPubMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DataChangedPubMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.TestProto.GeneratedModifiedReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataChangedPubMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataChangedPubMsg(DataChangedPubMsg other) : this() {
      turbineId_ = other.turbineId_;
      dateTime_ = other.dateTime_ != null ? other.dateTime_.Clone() : null;
      values_ = other.values_.Clone();
      needsWritingToRedis_ = other.needsWritingToRedis_;
      amount_ = other.amount_ != null ? other.amount_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataChangedPubMsg Clone() {
      return new DataChangedPubMsg(this);
    }

    /// <summary>Field number for the "TurbineId" field.</summary>
    public const int TurbineIdFieldNumber = 1;
    private string turbineId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TurbineId {
      get { return turbineId_; }
      set {
        turbineId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DateTime" field.</summary>
    public const int DateTimeFieldNumber = 2;
    private global::Google.Protobuf.TestProto.DateTime dateTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.TestProto.DateTime DateTime {
      get { return dateTime_; }
      set {
        dateTime_ = value;
      }
    }

    /// <summary>Field number for the "Values" field.</summary>
    public const int ValuesFieldNumber = 3;
    private static readonly pbc::MapField<string, string>.Codec _map_values_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 26);
    private readonly pbc::MapField<string, string> values_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Values {
      get { return values_; }
    }

    /// <summary>Field number for the "NeedsWritingToRedis" field.</summary>
    public const int NeedsWritingToRedisFieldNumber = 4;
    private bool needsWritingToRedis_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NeedsWritingToRedis {
      get { return needsWritingToRedis_; }
      set {
        needsWritingToRedis_ = value;
      }
    }

    /// <summary>Field number for the "Amount" field.</summary>
    public const int AmountFieldNumber = 5;
    private global::Google.Protobuf.TestProto.Decimal amount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.TestProto.Decimal Amount {
      get { return amount_; }
      set {
        amount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DataChangedPubMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DataChangedPubMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TurbineId != other.TurbineId) return false;
      if (!object.Equals(DateTime, other.DateTime)) return false;
      if (!Values.Equals(other.Values)) return false;
      if (NeedsWritingToRedis != other.NeedsWritingToRedis) return false;
      if (!object.Equals(Amount, other.Amount)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TurbineId.Length != 0) hash ^= TurbineId.GetHashCode();
      if (dateTime_ != null) hash ^= DateTime.GetHashCode();
      hash ^= Values.GetHashCode();
      if (NeedsWritingToRedis != false) hash ^= NeedsWritingToRedis.GetHashCode();
      if (amount_ != null) hash ^= Amount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TurbineId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TurbineId);
      }
      if (dateTime_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DateTime);
      }
      values_.WriteTo(output, _map_values_codec);
      if (NeedsWritingToRedis != false) {
        output.WriteRawTag(32);
        output.WriteBool(NeedsWritingToRedis);
      }
      if (amount_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Amount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TurbineId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TurbineId);
      }
      if (dateTime_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(DateTime);
      }
      values_.WriteTo(ref output, _map_values_codec);
      if (NeedsWritingToRedis != false) {
        output.WriteRawTag(32);
        output.WriteBool(NeedsWritingToRedis);
      }
      if (amount_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Amount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TurbineId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TurbineId);
      }
      if (dateTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DateTime);
      }
      size += values_.CalculateSize(_map_values_codec);
      if (NeedsWritingToRedis != false) {
        size += 1 + 1;
      }
      if (amount_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Amount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DataChangedPubMsg other) {
      if (other == null) {
        return;
      }
      if (other.TurbineId.Length != 0) {
        TurbineId = other.TurbineId;
      }
      if (other.dateTime_ != null) {
        if (dateTime_ == null) {
          DateTime = new global::Google.Protobuf.TestProto.DateTime();
        }
        DateTime.MergeFrom(other.DateTime);
      }
      values_.MergeFrom(other.values_);
      if (other.NeedsWritingToRedis != false) {
        NeedsWritingToRedis = other.NeedsWritingToRedis;
      }
      if (other.amount_ != null) {
        if (amount_ == null) {
          Amount = new global::Google.Protobuf.TestProto.Decimal();
        }
        Amount.MergeFrom(other.Amount);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TurbineId = input.ReadString();
            break;
          }
          case 18: {
            if (dateTime_ == null) {
              DateTime = new global::Google.Protobuf.TestProto.DateTime();
            }
            input.ReadMessage(DateTime);
            break;
          }
          case 26: {
            values_.AddEntriesFrom(input, _map_values_codec);
            break;
          }
          case 32: {
            NeedsWritingToRedis = input.ReadBool();
            break;
          }
          case 42: {
            if (amount_ == null) {
              Amount = new global::Google.Protobuf.TestProto.Decimal();
            }
            input.ReadMessage(Amount);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TurbineId = input.ReadString();
            break;
          }
          case 18: {
            if (dateTime_ == null) {
              DateTime = new global::Google.Protobuf.TestProto.DateTime();
            }
            input.ReadMessage(DateTime);
            break;
          }
          case 26: {
            values_.AddEntriesFrom(ref input, _map_values_codec);
            break;
          }
          case 32: {
            NeedsWritingToRedis = input.ReadBool();
            break;
          }
          case 42: {
            if (amount_ == null) {
              Amount = new global::Google.Protobuf.TestProto.Decimal();
            }
            input.ReadMessage(Amount);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DateTime : pb::IMessage<DateTime>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DateTime> _parser = new pb::MessageParser<DateTime>(() => new DateTime());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DateTime> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.TestProto.GeneratedModifiedReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DateTime() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DateTime(DateTime other) : this() {
      value_ = other.value_;
      scale_ = other.scale_;
      kind_ = other.kind_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DateTime Clone() {
      return new DateTime(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 1;
    private long value_;
    /// <summary>
    /// the offset (in units of the selected scale) from 1970/01/01
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    /// <summary>Field number for the "scale" field.</summary>
    public const int ScaleFieldNumber = 2;
    private global::Google.Protobuf.TestProto.DateTime.Types.TimeSpanScale scale_ = global::Google.Protobuf.TestProto.DateTime.Types.TimeSpanScale.Days;
    /// <summary>
    /// the scale of the timespan [default = DAYS]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.TestProto.DateTime.Types.TimeSpanScale Scale {
      get { return scale_; }
      set {
        scale_ = value;
      }
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 3;
    private global::Google.Protobuf.TestProto.DateTime.Types.DateTimeKind kind_ = global::Google.Protobuf.TestProto.DateTime.Types.DateTimeKind.Unspecified;
    /// <summary>
    /// the kind of date/time being represented [default = UNSPECIFIED]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.TestProto.DateTime.Types.DateTimeKind Kind {
      get { return kind_; }
      set {
        kind_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DateTime);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DateTime other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Value != other.Value) return false;
      if (Scale != other.Scale) return false;
      if (Kind != other.Kind) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Value != 0L) hash ^= Value.GetHashCode();
      if (Scale != global::Google.Protobuf.TestProto.DateTime.Types.TimeSpanScale.Days) hash ^= Scale.GetHashCode();
      if (Kind != global::Google.Protobuf.TestProto.DateTime.Types.DateTimeKind.Unspecified) hash ^= Kind.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Value != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(Value);
      }
      if (Scale != global::Google.Protobuf.TestProto.DateTime.Types.TimeSpanScale.Days) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Scale);
      }
      if (Kind != global::Google.Protobuf.TestProto.DateTime.Types.DateTimeKind.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Kind);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Value != 0L) {
        output.WriteRawTag(8);
        output.WriteSInt64(Value);
      }
      if (Scale != global::Google.Protobuf.TestProto.DateTime.Types.TimeSpanScale.Days) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Scale);
      }
      if (Kind != global::Google.Protobuf.TestProto.DateTime.Types.DateTimeKind.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Kind);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Value != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Value);
      }
      if (Scale != global::Google.Protobuf.TestProto.DateTime.Types.TimeSpanScale.Days) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Scale);
      }
      if (Kind != global::Google.Protobuf.TestProto.DateTime.Types.DateTimeKind.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DateTime other) {
      if (other == null) {
        return;
      }
      if (other.Value != 0L) {
        Value = other.Value;
      }
      if (other.Scale != global::Google.Protobuf.TestProto.DateTime.Types.TimeSpanScale.Days) {
        Scale = other.Scale;
      }
      if (other.Kind != global::Google.Protobuf.TestProto.DateTime.Types.DateTimeKind.Unspecified) {
        Kind = other.Kind;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Value = input.ReadSInt64();
            break;
          }
          case 16: {
            Scale = (global::Google.Protobuf.TestProto.DateTime.Types.TimeSpanScale) input.ReadEnum();
            break;
          }
          case 24: {
            Kind = (global::Google.Protobuf.TestProto.DateTime.Types.DateTimeKind) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Value = input.ReadSInt64();
            break;
          }
          case 16: {
            Scale = (global::Google.Protobuf.TestProto.DateTime.Types.TimeSpanScale) input.ReadEnum();
            break;
          }
          case 24: {
            Kind = (global::Google.Protobuf.TestProto.DateTime.Types.DateTimeKind) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the DateTime message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum TimeSpanScale {
        [pbr::OriginalName("DAYS")] Days = 0,
        [pbr::OriginalName("HOURS")] Hours = 1,
        [pbr::OriginalName("MINUTES")] Minutes = 2,
        [pbr::OriginalName("SECONDS")] Seconds = 3,
        [pbr::OriginalName("MILLISECONDS")] Milliseconds = 4,
        [pbr::OriginalName("TICKS")] Ticks = 5,
        /// <summary>
        /// dubious
        /// </summary>
        [pbr::OriginalName("MINMAX")] Minmax = 15,
      }

      public enum DateTimeKind {
        /// <summary>
        /// The time represented is not specified as either local time or Coordinated Universal Time (UTC).
        /// </summary>
        [pbr::OriginalName("UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// The time represented is UTC.
        /// </summary>
        [pbr::OriginalName("UTC")] Utc = 1,
        /// <summary>
        /// The time represented is local time.
        /// </summary>
        [pbr::OriginalName("LOCAL")] Local = 2,
      }

    }
    #endregion

  }

  public sealed partial class Decimal : pb::IMessage<Decimal>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Decimal> _parser = new pb::MessageParser<Decimal>(() => new Decimal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Decimal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.TestProto.GeneratedModifiedReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Decimal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Decimal(Decimal other) : this() {
      lo_ = other.lo_;
      hi_ = other.hi_;
      signScale_ = other.signScale_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Decimal Clone() {
      return new Decimal(this);
    }

    /// <summary>Field number for the "lo" field.</summary>
    public const int LoFieldNumber = 1;
    private ulong lo_;
    /// <summary>
    /// the first 64 bits of the underlying value
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Lo {
      get { return lo_; }
      set {
        lo_ = value;
      }
    }

    /// <summary>Field number for the "hi" field.</summary>
    public const int HiFieldNumber = 2;
    private uint hi_;
    /// <summary>
    /// the last 32 bis of the underlying value
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Hi {
      get { return hi_; }
      set {
        hi_ = value;
      }
    }

    /// <summary>Field number for the "signScale" field.</summary>
    public const int SignScaleFieldNumber = 3;
    private uint signScale_;
    /// <summary>
    /// the number of decimal digits (bits 1-16), and the sign (bit 0)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SignScale {
      get { return signScale_; }
      set {
        signScale_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Decimal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Decimal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Lo != other.Lo) return false;
      if (Hi != other.Hi) return false;
      if (SignScale != other.SignScale) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Lo != 0UL) hash ^= Lo.GetHashCode();
      if (Hi != 0) hash ^= Hi.GetHashCode();
      if (SignScale != 0) hash ^= SignScale.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Lo != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Lo);
      }
      if (Hi != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Hi);
      }
      if (SignScale != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(SignScale);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Lo != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Lo);
      }
      if (Hi != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Hi);
      }
      if (SignScale != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(SignScale);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Lo != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Lo);
      }
      if (Hi != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Hi);
      }
      if (SignScale != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SignScale);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Decimal other) {
      if (other == null) {
        return;
      }
      if (other.Lo != 0UL) {
        Lo = other.Lo;
      }
      if (other.Hi != 0) {
        Hi = other.Hi;
      }
      if (other.SignScale != 0) {
        SignScale = other.SignScale;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Lo = input.ReadUInt64();
            break;
          }
          case 16: {
            Hi = input.ReadUInt32();
            break;
          }
          case 24: {
            SignScale = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Lo = input.ReadUInt64();
            break;
          }
          case 16: {
            Hi = input.ReadUInt32();
            break;
          }
          case 24: {
            SignScale = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
